import { Roboto, Bebas_Neue } from 'next/font/google'
import './globals.css'
import "./styles/index.css"

export const roboto = Roboto({ subsets: ['latin'], weight: ["400"], display: "swap", variable: "--roboto-font" })
export const bebas = Bebas_Neue({subsets: ["latin"], weight: ["400"], display: "swap", variable: "--bebas-font"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${bebas.variable}`}>{children}</body>
    </html>
  )
}